; ==================================================
; KEYWORDS
; ==================================================

Keyword = isHuman|ActorTypeNPC,-ActorTypeAnimal,-ActorTypeCow,-ActorTypeCreature,-ActorTypeDaedra,-ActorTypeDragon,-ActorTypeDwarven,-ActorTypeFamiliar,-ActorTypeGhost,-ActorTypeGiant,-ActorTypeHorse,-ActorTypePrisoner,-ActorTypeTroll,-ActorTypeUndead


; ==================================================
; RAIN HOODS
; ==================================================

Item = SSH_BrownHood|isHuman|NONE|NONE|NONE|1|90
Item = SSH_GreyHood|AisHuman|NONE|NONE|NONE|1|50

; ==================================================
; SNOW HOODS
; ==================================================

Item = ArmorFurHoodBlack|isHuman|NONE|NONE|NONE|1|90
Item = ArmorFurHood|isHuman|NONE|NONE|NONE|1|50

; ==================================================
; RAIN CLOAKS
; ==================================================

Item = vol_Cape_Black|isHuman|-ArgonianRace,-KhajiitRace|NONE|NONE|1|80
Item = vol_Cape_Leather|isHuman|-ArgonianRace,-KhajiitRace|NONE|NONE|1|50

; ==================================================
; SNOW CLOAKS
; ==================================================

Item = vol_FurCloak_Black|isHuman|-ArgonianRace,-KhajiitRace|NONE|NONE|1|80
Item = vol_FurCloak_Brown|isHuman|-ArgonianRace,-KhajiitRace|NONE|NONE|1|50